FileNotFoundError in line 4 of /home/sattle00/Fachprojekt/fprdg1/Snakefile:
File b'table_for_reads.csv' does not exist
  File "/home/sattle00/Fachprojekt/fprdg1/Snakefile", line 4, in <module>
  File "/home/sattle00/miniconda3/envs/Fachprojekt-Reproduzierbare-Datenanlyse-Gruppe1/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
  File "/home/sattle00/miniconda3/envs/Fachprojekt-Reproduzierbare-Datenanlyse-Gruppe1/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
  File "/home/sattle00/miniconda3/envs/Fachprojekt-Reproduzierbare-Datenanlyse-Gruppe1/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
  File "/home/sattle00/miniconda3/envs/Fachprojekt-Reproduzierbare-Datenanlyse-Gruppe1/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
  File "/home/sattle00/miniconda3/envs/Fachprojekt-Reproduzierbare-Datenanlyse-Gruppe1/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
