Building DAG of jobs...
Creating conda environment envs/kallisto.yaml...
Downloading remote packages.
Environment for envs/kallisto.yaml created (location: .snakemake/conda/00faa953)
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	kallisto_idx
	4	kallisto_quant
	5

[Thu Jan 10 15:38:01 2019]
rule kallisto_idx:
    input: data/ref/transcriptome.chr21.fa
    output: kallisto/transcripts.idx
    jobid: 4

Activating conda environment: /home/sattle00/Fachprojekt/fprdg1/.snakemake/conda/00faa953
[Thu Jan 10 15:38:05 2019]
Finished job 4.
1 of 5 steps (20%) done

[Thu Jan 10 15:38:05 2019]
rule kallisto_quant:
    input: kallisto/transcripts.idx
    output: kallisto/b/abundance.h5
    jobid: 2
    wildcards: sample=b/abundance.h5

[Thu Jan 10 15:38:05 2019]
Error in rule kallisto_quant:
    jobid: 2
    output: kallisto/b/abundance.h5

RuleException:
CalledProcessError in line 26 of /home/sattle00/Fachprojekt/fprdg1/Snakefile:
Command ' set -euo pipefail;  kallisto quant -i kallisto/transcripts.idx -o  kallisto/b/abundance.h5 ' returned non-zero exit status 1.
  File "/home/sattle00/Fachprojekt/fprdg1/Snakefile", line 26, in __rule_kallisto_quant
  File "/home/sattle00/miniconda3/envs/fprdg1/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job kallisto_quant since they might be corrupted:
kallisto/b/abundance.h5
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/sattle00/Fachprojekt/fprdg1/.snakemake/log/2019-01-10T153734.861306.snakemake.log
